export default {
  // Instrumentos
  "guitarra": ["guitars", "electric guitars", "acoustic guitars", "classical guitars"],
  "guitarras": ["guitars", "electric guitars", "acoustic guitars", "classical guitars"],
  "bajo": ["basses", "electric basses", "acoustic basses"],
  "bajos": ["basses", "electric basses", "acoustic basses"],
  "batería": ["drums", "acoustic drums", "electronic drums"],
  "baterías": ["drums", "acoustic drums", "electronic drums"],
  "teclado": ["keyboards", "digital pianos", "stage pianos"],
  "teclados": ["keyboards", "digital pianos", "stage pianos"],
  "flauta": ["flutes", "recorders"],
  "flautas": ["flutes", "recorders"],
  "trompeta": ["trumpets"],
  "trompetas": ["trumpets"],
  "saxofón": ["saxophones"],
  "saxofones": ["saxophones"],
  "clarinete": ["clarinets"],
  "clarinetes": ["clarinets"],
  "violín": ["violins"],
  "violines": ["violins"],
  "ukelele": ["ukuleles"],
  "ukeleles": ["ukuleles"],

  // Accesorios
  "cuerda": ["strings", "guitar strings"],
  "cuerdas": ["strings", "guitar strings"],
  "caña": ["reeds", "woodwind reeds"],
  "cañas": ["reeds", "woodwind reeds"],
  "estuche": ["cases", "flightcases"],
  "estuches": ["cases", "flightcases"],
  "funda": ["bags", "soft cases"],
  "fundas": ["bags", "soft cases"],
  "atril": ["stands", "music stands"],
  "atriles": ["stands", "music stands"],
  "boquilla": ["mouthpieces"],
  "boquillas": ["mouthpieces"],
  "parche": ["drumheads"],
  "parches": ["drumheads"],
  "afinador": ["tuners"],
  "afinadores": ["tuners", "metronomes and tuners"],
  "púa": ["picks", "plectrums"],
  "púas": ["picks", "plectrums"],
  "pedal": ["pedals", "effects"],
  "pedales": ["pedals", "effects"],
  "baqueta": ["sticks", "mallets"],
  "baquetas": ["sticks", "mallets"],
  "cable": ["cables", "audio cables", "instrument cables"],
  "cables": ["cables", "audio cables", "instrument cables"],
  "soporte": ["stands"],
  "soportes": ["stands"],
  "sordina": ["mutes", "mute"],
  "sordinas": ["mutes", "mute"],
  "correa": ["straps"],
  "correas": ["straps"],
  "metrónomo": ["metronomes"],
  "metrónomos": ["metronomes"],

  // Audio
  "grabadora": ["recorders", "digital recorders"],
  "grabadoras": ["recorders", "digital recorders"],
  "interfaz": ["audio interfaces"],
  "interfaces": ["audio interfaces"],
  "mezclador": ["mixers", "mixing desks"],
  "mezcladores": ["mixers", "mixing desks"],
  "auricular": ["headphones"],
  "auriculares": ["headphones"],
  "micrófono": ["microphones"],
  "micrófonos": ["microphones"],
  "altavoz": ["speakers", "monitors", "pa speakers"],
  "altavoces": ["speakers", "monitors", "pa speakers"],
  "monitor": ["studio monitors"],
  "monitores": ["studio monitors"],
  "software": ["software", "music software", "plugins"]
};
